### ISSUE TITLE
Add ability for chapters [feature request]

### ISSUE THREAD

**Issue by kour1er** [crra/mp3binder#3]
Would it be possible to add the ability to make chapter markers for merging mp3 files when working with audiobooks? For example, if I have a directory of mp3 files that I'm merging, to make a new chapter marker for every file in the final outputted single mp3 file?

Thanks for the consideration

**Comment by crra** [comment]
Hey @kour1er,

thanks for reaching out. You mean: https://id3.org/id3v2-chapters-1.0?
I'll look into it.

**Comment by kour1er** [comment]
Yes exactly that - thanks very much!

**Comment by crra** [comment]
Hello @kour1er,

I've created a [pre-release with the support of the chapter markers](https://github.com/crra/mp3binder/releases/tag/4.1.0-pre1). Would you be so kind to check if the feature works as expected?

**Comment by kour1er** [comment]
Gosh that was quick work!

So I've tested a couple different sets of mp3 files to merge into a single chapterised mp3 file. When I use the --verbose flag I can see the chapter timestamp being generated but in the final file I'm not seeing any chapter data. As a side issue, if I use the --cover flag, that information doesn't appear to be added either, so I wonder if the additional data just isn't being written to the final file? I checked with the previous release and --cover works there for me but not in the new release.

For testing, I'm using [Bound](https://bound.timbueno.com) on iOS, [ffprobe](https://ffmpeg.org) on the command line with -show_chapters flag and [IINA](https://iina.io) for macOS (a front end for mpv).

Am I missing a setting somewhere? This is with version 4.1.0+pre1

**Comment by crra** [comment]
Sorry that it didn't work. Thanks for the ffprobe link for inspecting chapters.

As for the covers, this is very strange. It works on my machine (TM) :) with magic discovery and `--cover foo.jpg`. Can you share a link to the cover?

![with_cover](https://user-images.githubusercontent.com/8239189/149848948-28c560f0-ada2-41e0-b8ae-4022e34d2246.png)

**Comment by kour1er** [comment]
re: ffprobe/chapters - please let me know if I can provide further information on that.

re: cover - so let's take something popular as an example: how about [The Martian](https://m.media-amazon.com/images/I/414J3xG+7+L._SL500_.jpg). It's a 500x500 pixel image so I don't think that should be outside of spec.

If I try using that jpg on the pre-release the cover isn't added to the mp3 on my machine (doesn't work TM?). But using version 4.0.0 it does. I'm validating that using [Meta](https://www.nightbirdsevolve.com/meta/) on macOS. I don't know 'magic discovery' and couldn't find an obvious match from a search, could you link to it and I can test here with that tool too?

Cheers

**Comment by crra** [comment]
Oh shoot. [kid3](https://kid3.kde.org/) (which I used for testing) shows the meta data, but any other tool (e.g. the finder or [id3editor](http://www.pa-software.com/id3editor/)) shows nothing. Maybe it's chapter related or due to the update of [id3v2](https://github.com/bogem/id3v2/tree/main/v2) to the latest v2.

I see that the header for "ID3" is missing in the file, but the data was written (that's why kid3 was showing it), so I assume it must be a corrupt file.

![hex](https://user-images.githubusercontent.com/8239189/150212839-abc7140a-f848-431c-b7a3-bfacdd90c77d.png)

**Comment by kour1er** [comment]
Interesting - I checked with kid3 on my system and it also shows the correct image in both the old and prerelease versions. But other tools (IINA, VLC, Meta, Finder, Bound etc) don't show the cover art on mp3s generated by the prerelease version. If I inspect the hex of an mp3 created by the prerelease and the current release I see the same ID3 information you found too. So that's weird :)

Also, on the original matter of the chapter embedding, I noticed in kid3, that although it does show embedded chapter information it doesn't appear to have the "Table of Contents" "toc" tag. I think that's a required element? Haven't been able to find a good link for that. Just wonder if that might be it?

**Comment by crra** [comment]
Baby steps: merging two mp3 files without id3 tags yield the same result in 4.0.0 and head.

**Comment by crra** [comment]
After adding one tag, the position of the ID3 tag in reference to the Xing tag is different. 4.0.0 shows the tack number in the editor, head doesn't.

4.0.0 (left) head (right)

![onetag](https://user-images.githubusercontent.com/8239189/150432844-c3db542e-4772-4457-a260-6f6e21304b13.png)

**Comment by crra** [comment]
I've changed the order when the id3 tags is written, because I  wanted to parse each file once for the duration:

- 4.0.0:  write metadata, bind
- head: bind, write metadata

My guess is that the file offset of the output file is not properly set (stateful) and I'm corrupting the file with a random write.

**Comment by crra** [comment]
Mhh, the id3 tag is now written at the end, but still not working. Next check is id3v2.4 (UTF-8) vs id3v2.3 (UTF-8). I've also noticed that any other id3 editor rewrites the file so that the id3 tag is always at the beginning. I know that this was a requirement for id3v1.

**Comment by crra** [comment]
Hello 2003: https://hydrogenaud.io/index.php?topic=10764.msg108795#msg108795: "Foobar with the ID3v2 plugin does ID3v2.4 as long as they are at the beginning of the file."

**Comment by crra** [comment]
If I write the ID3 tag at the beginning of the file, any editor recognizes the tag. I always thought it would be better so that music players don't need to parse the whole file. But I discarded it with the chapter change as "premature optimization".

**Comment by kour1er** [comment]
Interesting - the 'root of all evil' strikes again :)

**Comment by crra** [comment]
> Interesting - the 'root of all evil' strikes again :)
Thanks for the working title of the [next pre-release](https://github.com/crra/mp3binder/releases/tag/4.1.0-pre2). You may want to give it a try. I'm not sure if I want to keep this specific implementation (using a temporary file to ensure the frame order) but any other solution this is more complicated and more error prone (e.g. own parser for frame offsets and delay the actual read till the end). Maybe a temporary file is not so bad at all.

**Comment by crra** [comment]
- [ ]  TOC is essential (currently not supported by the used library, needs investigation)
- [x] Some apps are picky about the Identifier of the Chapter value
- [ ] start/end offset is required in some players (should be possible)

**Comment by crra** [comment]
@kour1er it seams like you have the wider variety of tools to check the chapter support. Would you be so kind to test it with the [new beta](https://github.com/crra/mp3binder/releases/tag/4.1.0-pre3)? I extended the underlying library because it didn't support chapter TOCs.

**Comment by kour1er** [comment]
Just to give you quick feedback - progress! Chapters are now working in IINA, Books (Apple desktop app), Bound (iOS) and BookPlayer (iOS). Nice work on the library work. 👍 

One regression, the artist, title and album (so author and book as it were) don't appear to be written to the final file. I don't see those tags in Kid3 either. This is only from testing one book running it through your tool a few times. Cover is working fine.

**Comment by crra** [comment]
Now is the time to add those missing tests :)

**Comment by crra** [comment]
> One regression, the artist, title and album (so author and book as it were) don't appear to be written to the final file.

Can you post the command line here? I assume it contains spaces and the string must be quoted. For example: `--tapply TIT2=foo,TALB=bar` results in:
![unquoted](https://user-images.githubusercontent.com/8239189/151695120-19d5b725-605d-497c-83bb-589b67e76658.png)
and `--tapply 'TIT2="Foo foo",TALB=bar'` results in:
![quoted](https://user-images.githubusercontent.com/8239189/151695166-42cc61c4-5178-4203-a341-e030d8db4b5b.png)

This is currently broken: `--tapply TIT2="Foo foo",TALB=bar`
![onlyfield](https://user-images.githubusercontent.com/8239189/151695239-9ef64ef3-2dbb-483b-83f5-2adb603080a6.png)

**Comment by crra** [comment]
With #5 closed, I think it becomes more user-friendly if one uses `--tapply TIT2="Foo foo"`.

**Comment by kour1er** [comment]
> I assume it contains spaces or special chars (`,`, `=`,`:`) and then the string must be quoted.

Doh! You're entirely correct. Can't believe I didn't think of that. 

So I've tested three more books using the most recent beta you sent and all seems to be working correctly! I will continue to test some more and of course with the new version with the more 'user-friendly' quote version too. Congrats on the solution.

(I still can't get over how fast the tool is)

**Comment by crra** [comment]
I consider the current head stable enough for new official release. Please feel free to open new issues any time.
