### ISSUE TITLE
User error, I am sure

### ISSUE THREAD

**Issue by jvblue** [crra/mp3binder#38]
I have Task installed and I ran it in the mp3binder dir. it looks like it was successful, but when I try to run, I get the zsh: command not found.

Task and Go are new to me, so i am sure this is a user error.  Any suggestions? Working on a Mac.

`user@audiobooks mp3binder-main % task
fatal: not a git repository (or any of the parent directories): .git
task: [default:test] go test -cover -race ./...
task: [default:prepare] mkdir -p dist
?   	github.com/crra/mp3binder/cmd/tui	[no test files]
?   	github.com/crra/mp3binder/io/rewindingreader	[no test files]
?   	github.com/crra/mp3binder/mp3binder	[no test files]
?   	github.com/crra/mp3binder/mp3binder/tags	[no test files]
ok  	github.com/crra/mp3binder/cli	(cached)	coverage: 68.6% of statements
ok  	github.com/crra/mp3binder/encoding/keyvalue	(cached)	coverage: 100.0% of statements
ok  	github.com/crra/mp3binder/slice	(cached)	coverage: 17.9% of statements
ok  	github.com/crra/mp3binder/value	(cached)	coverage: 100.0% of statements
task: [default:build-for] go build -trimpath -ldflags="-w -s -X main.name="mp3binder" -X main.version="" -X main.realm="mp3binder" -extldflags '-static'" -a -buildvcs=false -o dist/darwin_amd64/mp3binder ./cmd/tui`

**Comment by crra** [comment]
I'll look into it.

**Comment by jvblue** [comment]
I was able to resolve. Found the app in the darwin folder, and moved. All
at this moment looks to be working (calling the command). Have not tested
on files yet

**Comment by crra** [comment]
Let's start step by step: did you check out via git or did you just unzip a snapshot?

According to the error log you may did the later. You should use the `git clone https://github.com/crra/mp3binder.git` command. The reason for this is, that the build script uses the git history/tags to "bake in" the version number in the final binary. If you call the build command in a non-git directory this just fails.

However you could also use the pre-built binary releases ;)

**Comment by crra** [comment]
> I was able to resolve. Found the app in the darwin folder, and moved.
Feel free to come back to me if there is any issue.
